platform :ios, '8.0'

# For latest release in cocoapods
pod 'JSQSystemSoundPlayer'
# pod 'JSQMessagesViewController', '~> 7.3.4'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ASIHTTPRequest'
pod 'Reachability', '~> 3.2'
pod 'NSData+Base64'
pod 'JSONModel'
pod 'NSString+Emoji'

target 'AIChatBots' do
	
end
